import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.LOCALAPPDATA + '/npm-cache/_npx/b234c773f454f454/node_modules/playwright');
const b = await chromium.launch();
let p = await (await b.newContext({ viewport: { width: 1536, height: 864 }, deviceScaleFactor: 2 })).newPage();
p.on('pageerror', e => console.error('ERR:', e.message));
await p.goto('http://localhost:5173/?k=eastside2026', { waitUntil: 'networkidle' });
await p.waitForTimeout(1800);
await p.screenshot({ path: './_screens/h-owner-full.png', fullPage: true });
await p.close();
let m = await (await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })).newPage();
await m.goto('http://localhost:5173/?k=eastside2026', { waitUntil: 'networkidle' });
await m.waitForTimeout(1600);
await m.evaluate(() => document.querySelector('[data-p="leads"]').click());
await m.waitForTimeout(1000);
await m.evaluate(() => document.querySelector('.trow[data-id]').click());
await m.waitForTimeout(2400);
await m.screenshot({ path: './_screens/h-modal-mob.png' });
await b.close();
console.log('done');
