import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.LOCALAPPDATA + '/npm-cache/_npx/b234c773f454f454/node_modules/playwright');
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 2 })).newPage();
p.on('pageerror', e => console.error('ERR:', e.message));
await p.goto('https://eastside-crm.vercel.app/?k=eastside2026', { waitUntil: 'networkidle' });
await p.waitForTimeout(3000);
await p.screenshot({ path: './_screens/prod-owner.png' });
const hasStat = await p.$('.statbar .sdot');
console.log('new build live (sdot present):', !!hasStat);
await b.close();
